services:

  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - mode: ingress
        target: 6379
        published: 6379
        protocol: tcp

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - mode: ingress
        target: 5432
        published: 5432
        protocol: tcp

  backend:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 & celery -A core beat"
    ports:
      - mode: ingress
        target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: ./core
        target: /app
        bind:
          create_host_path: true
    depends_on:
      - redis
      - postgres
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  worker:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - type: bind
        source: ./core
        target: /app
        bind:
          create_host_path: true
    depends_on:
      - redis
      - backend
      - postgres

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # where smtp4dev stores the database
      - smtp4dev-data:/smtp4dev
    environment:
      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:
  postgres-data:
