# Generated by Django 3.2.25 on 2024-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="accounts/anonymous-person.jpg", upload_to="accounts/"
            ),
        ),
    ]
