# Generated by Django 3.2.25 on 2024-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default="admin", max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
